"""empty message

Revision ID: 847694232971
Revises: 4e095a20e203
Create Date: 2020-02-27 16:53:05.925101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847694232971'
down_revision = '4e095a20e203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
